services:
  db:
    image: mysql
    environment:
      MYSQL_USER: wws
      MYSQL_PASSWORD: wws
      MYSQL_ROOT_PASSWORD: wws
      MYSQL_DATAABASE: wws
    ports:
      - "8306:3306"
    container_name: db
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  session:
    image: redis
    ports:
      - "8379:6379"
    container_name: session-db
    healthcheck:
      test: redis-cli --raw  incr ping
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  rtmp:
    build: ./rtmp/rtmp
    ports:
      - "1935:1935"
      - "8004:8004"
    container_name: rtmp
    volumes:
      - ./rtmp/records:/records
    develop:
      watch:
        - action: rebuild
          path: ./rtmp/rtmp/nginx.conf

  auth:
    build: ./auth
    depends_on:
      - db
      - session
    ports:
      - "8000:8000"
    container_name: auth
    develop:
      watch:
        - action: sync
          path: ./auth/src
          target: /app/src

        - action: rebuild
          path: ./auth/package.json
          target: /app/package.json

        - action: rebuild
          path: ./auth/.env
          target: /app/.env

  api:
    build: ./api
    depends_on:
      - db
      - session
    ports:
      - "8001:8001"
    container_name: api
    develop:
      watch:
        - action: sync
          path: ./api/src
          target: /app/src

        - action: rebuild
          path: ./api/package.json
          target: /app/package.json

        - action: rebuild
          path: ./api/.env
          target: /app/.env

  client:
    build: ./client
    ports:
      - "8080:5173"
    container_name: client
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: /app/src

        - action: rebuild
          path: ./client/package.json
          target: /app/package.json

        - action: rebuild
          path: ./client/.env
          target: /app/.env

  live-session-hub:
    build: ./live-session-hub
    ports:
      - "8005:8005"
    container_name: live-session-hub
    develop:
      watch:
        - action: sync
          path: ./live-session-hub/src
          target: /app/src

        - action: rebuild
          path: ./live-session-hub/package.json
          target: /app/package.json

        - action: rebuild
          path: ./live-session-hub/.env
          target: /app/.env
