version: "3.9"

services:
  db:
    image: mysql
    environment:
      MYSQL_USER: wws
      MYSQL_PASSWORD: wws
      MYSQL_ROOT_PASSWORD: wws
      MYSQL_DATAABASE: wws
    ports:
      - "8306:3306"
    container_name: db
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  session:
    image: redis
    ports:
      - "8379:6379"
    container_name: session-db
    healthcheck:
      test: redis-cli --raw  incr ping
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  rtmp:
    build: ./rtmp/rtmp
    ports:
      - "1935:1935"
      - "8004:8004"
    container_name: rtmp
    volumes:
      - ./rtmp/records:/records

  auth:
    build: ./auth
    depends_on:
      - db
      - session
    ports:
      - "8000:8000"
    container_name: auth

  api:
    build: ./api
    depends_on:
      - db
      - session
    ports:
      - "8001:8001"
    container_name: api
